### ISSUE TITLE
Sensor or listener is null" error when connecting using Tap to Pay mode on Sunmi devices

### ISSUE THREAD

**Issue by zontaluca** [stripe/stripe-terminal-android#562]
## Summary
Connection to Tap to Pay device (Sunmi V3 Mix, D3 Mini) fails with "sensor or listener is null" error. The app successfully discovers the device but gets stuck in the connecting state.

## Code to reproduce
While no specific code snippet is provided, the issue occurs when attempting to connect to a Tap to Pay reader using the Stripe Terminal SDK. The logs show a call to `Terminal.connectReader` with a device serial number, followed by the connection attempt that never completes.

## Android version
Android 13

## Impacted devices (Android devices or readers)
- Android devices: Sunmi V3 Mix EDLA_GL, Sunmi D3 Mini
- Reader type: TAP_TO_PAY_DEVICE

## SDK version
Stripe Terminal SDK version 4.2.0

## Other information
Sunmi OS version: 4.0.17

The app was built in release mode to enable Tap to Pay functionality.

The logs show that the connection process starts successfully:
1. Device is discovered with serial number
2. Connection status changes from NOT_CONNECTED to CONNECTING
3. The API call to activate the connection token succeeds with status code 200
4. The process then fails with "sensor or listener is null" error from SensorManager

Key log entries:
```
2025-03-16 17:16:27.177 10854-10854 StripeTerminal com.stripe.example D class=Terminal message=connectReader serial_number=<UUID>
2025-03-16 17:16:27.181 10854-10943 StripeTerminal com.stripe.example D class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
2025-03-16 17:16:28.188 10854-10943 RestResponse com.stripe.example I REST response with code 200 received
2025-03-16 17:16:28.273 11007-11029 SensorManager com.stripe.example E sensor or listener is null
```

The device is attempting to use a Sunmi V3 Mix for Tap to Pay, which is listed as a supported device in the Stripe documentation (https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#device-types). The connection process appears to fail during sensor initialization, which might be related to NFC capabilities.

**Comment by hrueger** [comment]
Hi,
chiming in here. We just spend 2 hours debugging until I found that someone has already reported this.
We can also confirm that this is a new regression in sdk version 4.2.0. With 4.1.0 everything works just fine.

**Comment by hrueger** [comment]
Stripe Support wanted videos, so I thought I'd also upload them here:

ADB Logcat Output:
https://github.com/user-attachments/assets/7ae2c0b8-8854-496f-91c4-5b15ff4adf4d
<details>
<summary>As Text</summary>

```
2025-03-22 09:14:01.478  8303-8394  ProfileInstaller        mek.stripe_terminal_example          D  Installing profile for mek.stripe_terminal_example
2025-03-22 09:14:56.462  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.locationWhenInUse: PermissionStatus.granted
2025-03-22 09:14:56.463  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.bluetooth: PermissionStatus.granted
2025-03-22 09:14:56.464  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.bluetoothScan: PermissionStatus.granted
2025-03-22 09:14:56.465  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.bluetoothConnect: PermissionStatus.granted
2025-03-22 09:14:56.467  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.locationWhenInUse: ServiceStatus.enabled
2025-03-22 09:14:56.481  8303-8303  flutter                 mek.stripe_terminal_example          I  Permission.bluetooth: ServiceStatus.enabled
2025-03-22 09:14:56.528  8303-8303  BatchDispatcher         mek.stripe_terminal_example          I  Already initialized.
2025-03-22 09:14:56.533  8303-8455  QueueFileCollector      mek.stripe_terminal_example          V  terminal_sdk_wire_traces_2 ready to use with 0 entries and 32 bytes.
2025-03-22 09:14:56.542  8303-8459  QueueFileCollector      mek.stripe_terminal_example          V  terminal_sdk_wire_events ready to use with 0 entries and 32 bytes.
2025-03-22 09:14:56.543  8303-8460  QueueFileCollector      mek.stripe_terminal_example          V  terminal_sdk_wire_metrics ready to use with 0 entries and 32 bytes.
2025-03-22 09:14:56.552  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=TerminalSdkManager message="Application version info" minSdkVersion=26 targetSdkVersion=35 compileSdkVersion=35
2025-03-22 09:14:56.559  8303-8303  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalSdkManager message="taptopay module detected"
2025-03-22 09:14:57.622  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=TerminalSdkManager app_language=KOTLIN
2025-03-22 09:14:57.623  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=LocationHandler message=startListening
2025-03-22 09:14:57.688  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=ConnectionTokenRepository message=refreshToken
2025-03-22 09:14:57.746  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=DefaultOfflineTraceManager message="Start forwarding" isAlreadyForwarding=null
2025-03-22 09:14:57.753  8303-8476  StripeTerminal          mek.stripe_terminal_example          D  class=DefaultOfflineTraceManager message="Forwarding started" hasAccount=true hasNetwork=true
2025-03-22 09:14:58.200  8303-8303  flutter                 mek.stripe_terminal_example          I  {"object":"terminal.connection_token","secret":"redacted"}
2025-03-22 09:14:58.201  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=ConnectionTokenRepository message=fetchConnectionToken.onSuccess
2025-03-22 09:14:59.148  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=Terminal message=listLocations
2025-03-22 09:14:59.151  8303-8463  StripeTerminal          mek.stripe_terminal_example          D  class=ApiClient message=listLocations
2025-03-22 09:14:59.419  8303-8463  StripeTerminal          mek.stripe_terminal_example          I  class=RestClient message="url=https://api.stripe.com/v1/terminal/locations request={}"
2025-03-22 09:14:59.437  8303-8463  TrafficStats            mek.stripe_terminal_example          D  tagSocket(130) with statsTag=0xffffffff, statsUid=-1
2025-03-22 09:14:59.916  8303-8463  RestResponse            mek.stripe_terminal_example          I  REST response with code 200 received
2025-03-22 09:14:59.916  8303-8463  RestResponse            mek.stripe_terminal_example          I  request-id: req_n4R4rBaNkwmzVT
2025-03-22 09:14:59.957  8303-8463  StripeTerminal          mek.stripe_terminal_example          I  class=RestClient message="url=https://api.stripe.com/v1/terminal/locations status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, HEAD, PUT, PATCH, POST, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, Stripe-Should-Retry, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=1002, content-security-policy=base-uri 'none'; default-src 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; script-src 'self' 'report-sample'; style-src 'self'; worker-src 'none'; upgrade-insecure-requests; report-uri https://q.stripe.com/csp-violation?q=tX2guqYncfomEWe-Mk2AXqXsVToGidy2-03lWTRLHKQk8LH5Df1u7KLOHTP3E079LfXHt4sYD--fS1tg, content-type=application/json, cross-origin-opener-policy-report-only=same-origin; report-to="coop", date=Sat, 22 Mar 2025 08:14:59 GMT, idempotency-key=1742631299415unknowno2TGdVFO, report-to={"group":"coop","max_age":8640,"endpoints":[{"url":"https://q.stripe.com/coop-report"}],"include_subdomains":true}, reporting-endpoints=coop="https://q.stripe.com/coop-report", request-id=req_n4R4rBaNkwmzVT, server=nginx, strict-transport-security=max-age=63072000; includeSubDomains; preload, stripe-version=2019-02-19, vary=Origin, x-stripe-priority-routing-enabled=true, x-stripe-routing-context-priority-tier=api-testmode, x-wc=AB} response={"data":[{"address":{"city":"Rettenberg","country":"DE","line1":"Auf d. Egg","line2":"","postalCode":"87549","state":"BY"},"displayName":"[VVK-Stelle] AK Alpe Müllers Berg","id":"tml_F9OkIgyIhKAr5k","livemode":false,"metadata":{"officeId":"98e6e9d9-5823-485b-b22d-27c902830bbe"}},{"address":{"city":"Marktoberdorf","country":"DE","line1":"Schwabenstr. 58","line2":"8","postalCode":"87616","state":"BY"},"displayName":"Office 3c5789da-7307-45d6-a084-aaa28209dd5f","id":"tml_F6ZhQALwDHqrfm","livemode":false,"metadata":{"officeId":"3c5789da-7307-45d6-a084-aaa28209dd5f"}}],"hasMore":false}"
2025-03-22 09:15:03.412  8303-8303  OnBackInvokedCallback   mek.stripe_terminal_example          W  OnBackInvokedCallback is not enabled for the application.
                                                                                                    Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
2025-03-22 09:15:05.978  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=Terminal message=discoverReaders
2025-03-22 09:15:05.979  8303-8303  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalSession message=enqueueOperation operation=DiscoverReadersOperation
2025-03-22 09:15:05.981  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalStatusManager message=startDiscovery.
2025-03-22 09:15:05.983  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ProxyTerminalListener message=onConnectionStatusChange(DISCOVERING)
2025-03-22 09:15:05.984  8303-8303  flutter                 mek.stripe_terminal_example          I  Connection Status Changed: discovering
2025-03-22 09:15:05.988  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=AdapterRepository message="Switching adapters" from=null to=CotsAdapter
2025-03-22 09:15:06.015  8303-8303  pool-10-thread-         mek.stripe_terminal_example          W  type=1400 audit(0.0:680): avc: denied { search } for name="cache" dev="dm-44" ino=143 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tcontext=u:object_r:cache_file:s0 tclass=dir permissive=0 app=mek.stripe_terminal_example
2025-03-22 09:15:06.138  8303-8464  StripeTerminal          mek.stripe_terminal_example          D  class=AidlRpcClient message=bindToService action= packageName=mek.stripe_terminal_example className=com.stripe.cots.aidlservice.CotsService
2025-03-22 09:15:06.158  8303-8464  StripeTerminal          mek.stripe_terminal_example          D  class=AidlRpcClient message="Context::bindService completed" success=true
---------------------------- PROCESS STARTED (8520) for package mek.stripe_terminal_example ----------------------------
2025-03-22 09:15:07.055  8520-8520  :stripetaptopay         mek.stripe_terminal_example          W  type=1400 audit(0.0:889): avc: denied { getattr } for path="/sys/kernel/tracing/trace_marker" dev="tracefs" ino=8855 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0 app=mek.stripe_terminal_example
2025-03-22 09:15:07.437  8520-8520  EngineFactory           mek.stripe_terminal_example          I  Provider GmsCore_OpenSSL not available
2025-03-22 09:15:07.704  8520-8541  SCP                     mek.stripe_terminal_example          E  Asset is compreseed: l76c51f537231fb60896497ca.szip
2025-03-22 09:15:07.750  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=AidlServiceConnection message=onServiceConnected() connectionOwner=CotsClient componentName=ComponentInfo{mek.stripe_terminal_example/com.stripe.cots.aidlservice.CotsService}
2025-03-22 09:15:07.754  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=AidlRpcClient message=makeRequest service=COTS_SERVICE method=DISCOVER requestId=0
2025-03-22 09:15:07.932  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=ProxyDiscoveryListener message=onUpdateDiscoveredReaders([76df4f57-1f7c-4a8a-9652-d21acbda77ef])
2025-03-22 09:15:07.942  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalStatusManager message=endDiscovery.
2025-03-22 09:15:07.942  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
2025-03-22 09:15:07.944  8303-8303  flutter                 mek.stripe_terminal_example          I  Connection Status Changed: notConnected
2025-03-22 09:15:09.620  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=Terminal message=connectReader serial_number=76df4f57-1f7c-4a8a-9652-d21acbda77ef
2025-03-22 09:15:09.623  8303-8463  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalSession message=enqueueOperation operation=ConnectReaderOperation
2025-03-22 09:15:09.634  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalStatusManager message=reportReaderConnecting. reader="Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}" connectionConfiguration="TapToPayConnectionConfiguration{failIfInUse=false, locationRegistration=UseId(locationId=tml_F6ZhQALwDHqrfm), autoReconnectOnUnexpectedDisconnect=true}"
2025-03-22 09:15:09.635  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
2025-03-22 09:15:09.638  8303-8303  flutter                 mek.stripe_terminal_example          I  Connection Status Changed: connecting
2025-03-22 09:15:09.640  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=TerminalStatusManager message=emitReaderConnectivityEvent. readerConnectivityEvent="Connecting(reader=Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}, connectionConfiguration=TapToPayConnectionConfiguration{failIfInUse=false, locationRegistration=UseId(locationId=tml_F6ZhQALwDHqrfm), autoReconnectOnUnexpectedDisconnect=true})"
2025-03-22 09:15:09.643  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ProxyAdapter message=connectReader reader=null deviceInfo="DeviceInfo{device_class=READER, device_uuid=76df4f57-1f7c-4a8a-9652-d21acbda77ef, hardware_model=HardwareModel{cots_hardware=COTSHardware{name=V3_MIX_EDLA_GL, model=, manufacturer=SUNMI, mobile_os=ANDROID}}, app_model=ApplicationModel{app_id=, app_version=unknown}, device_ip=, host_hw_version=unknown, host_os_version=, hostname=, connectivity_source=UNKNOWN, bbpos_firmware=, bbpos_base_config=, bbpos_key_profile=, bbpos_rom=, stripe_config_hash=}" connectionConfigurationType=TapToPayConnectionConfiguration
2025-03-22 09:15:09.643  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=CotsAdapter message=connectReader reader=null deviceInfo="DeviceInfo{device_class=READER, device_uuid=76df4f57-1f7c-4a8a-9652-d21acbda77ef, hardware_model=HardwareModel{cots_hardware=COTSHardware{name=V3_MIX_EDLA_GL, model=, manufacturer=SUNMI, mobile_os=ANDROID}}, app_model=ApplicationModel{app_id=, app_version=unknown}, device_ip=, host_hw_version=unknown, host_os_version=, hostname=, connectivity_source=UNKNOWN, bbpos_firmware=, bbpos_base_config=, bbpos_key_profile=, bbpos_rom=, stripe_config_hash=}" connectionConfigurationType=TapToPayConnectionConfiguration
2025-03-22 09:15:09.643  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalStatusManager message=readerSerialUpdatedWhileConnecting. reader="Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}"
2025-03-22 09:15:09.644  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=TerminalStatusManager message=readerActivationStarted.
2025-03-22 09:15:09.644  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=OnlineDirectResourceRepository message=activateReader reader="Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}" connectionConfiguration="TapToPayConnectionConfiguration{failIfInUse=false, locationRegistration=UseId(locationId=tml_F6ZhQALwDHqrfm), autoReconnectOnUnexpectedDisconnect=true}"
2025-03-22 09:15:09.645  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ConnectionTokenRepository message=refreshToken
2025-03-22 09:15:09.646  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ApiClient message=activateReader reader="Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}" connectionConfig="TapToPayConnectionConfiguration{failIfInUse=false, locationRegistration=UseId(locationId=tml_F6ZhQALwDHqrfm), autoReconnectOnUnexpectedDisconnect=true}"
2025-03-22 09:15:09.646  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ApiRequestFactory message=activateReader reader="Reader{deviceType=TAP_TO_PAY_DEVICE, serialNumber=76df4f57-1f7c-4a8a-9652-d21acbda77ef}" connectionConfig="TapToPayConnectionConfiguration{failIfInUse=false, locationRegistration=UseId(locationId=tml_F6ZhQALwDHqrfm), autoReconnectOnUnexpectedDisconnect=true}" remotePosSdkVersionInfo=null remotePosDeviceInfo=null
2025-03-22 09:15:09.647  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ApiRequestFactory message="falling back to using local pos device info" EmbeddedConnectionConfiguration?=false device-uuid?=null
2025-03-22 09:15:09.649  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=ApiRequestFactory message="Created ActivateConnectionTokenRequest" request="ActivateConnectionTokenRequest{pos_device_id=7f649cbf-6900-4f39-bf81-c0da20a4cd13, device_type=mobile_phone_reader, device_serial_number=76df4f57-1f7c-4a8a-9652-d21acbda77ef, reader_=DeviceInfo{device_class=READER, device_uuid=76df4f57-1f7c-4a8a-9652-d21acbda77ef, hardware_model=HardwareModel{cots_hardware=COTSHardware{name=V3_MIX_EDLA_GL, model=, manufacturer=SUNMI, mobile_os=ANDROID}}, app_model=ApplicationModel{app_id=, app_version=unknown}, device_ip=, host_hw_version=unknown, host_os_version=, hostname=, connectivity_source=UNKNOWN, bbpos_firmware=, bbpos_base_config=, bbpos_key_profile=, bbpos_rom=, stripe_config_hash=}, pos_device_info=DeviceInfo{device_class=POS, device_uuid=7f649cbf-6900-4f39-bf81-c0da20a4cd13, hardware_model=HardwareModel{pos_info=POSInfo{description=V3_MIX}}, app_model=ApplicationModel{app_id=mek.stripe_terminal_example, app_version=1.0.0}, device_ip=, host_hw_version=V3_MIX_EDLA_GL, host_os_version=13, hostname=, connectivity_source=UNKNOWN, bbpos_firmware=, bbpos_base_config=, bbpos_key_profile=, bbpos_rom=, stripe_config_hash=}, pos_version_info=VersionInfoPb{client_type=ANDROID_SDK, client_version=4.3.0, version_code=0}, register_to_location=tml_F6ZhQALwDHqrfm, expand=[account_ref.store_id], generate_offline_stripe_session_token=false}"
2025-03-22 09:15:09.701  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate request={"deviceSerialNumber":"76df4f57-1f7c-4a8a-9652-d21acbda77ef","deviceType":"mobile_phone_reader","expand":["account_ref.store_id"],"generateOfflineStripeSessionToken":false,"posDeviceId":"7f649cbf-6900-4f39-bf81-c0da20a4cd13","posDeviceInfo":{"appModel":{"appId":"mek.stripe_terminal_example","appVersion":"1.0.0"},"deviceClass":"POS","deviceUuid":"7f649cbf-6900-4f39-bf81-c0da20a4cd13","hardwareModel":{"posInfo":{"description":"V3_MIX"}},"hostHwVersion":"V3_MIX_EDLA_GL","hostOsVersion":"13"},"posVersionInfo":{"clientType":"ANDROID_SDK","clientVersion":"4.3.0"},"reader":{"appModel":{"appVersion":"unknown"},"deviceClass":"READER","deviceUuid":"76df4f57-1f7c-4a8a-9652-d21acbda77ef","hardwareModel":{"cotsHardware":{"manufacturer":"SUNMI","mobileOs":"ANDROID","name":"V3_MIX_EDLA_GL"}},"hostHwVersion":"unknown"},"registerToLocation":"tml_F6ZhQALwDHqrfm"}"
2025-03-22 09:15:10.046  8303-8303  flutter                 mek.stripe_terminal_example          I  {"object":"terminal.connection_token","secret":"redacted"}
2025-03-22 09:15:10.049  8303-8303  StripeTerminal          mek.stripe_terminal_example          D  class=ConnectionTokenRepository message=fetchConnectionToken.onSuccess
2025-03-22 09:15:10.313  8303-8516  RestResponse            mek.stripe_terminal_example          I  REST response with code 200 received
2025-03-22 09:15:10.313  8303-8516  RestResponse            mek.stripe_terminal_example          I  request-id: req_meAsYPd1zisb63
2025-03-22 09:15:10.339  8303-8516  StripeTerminal          mek.stripe_terminal_example          I  class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, HEAD, PUT, PATCH, POST, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, Stripe-Should-Retry, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=1042, content-security-policy=base-uri 'none'; default-src 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; script-src 'self' 'report-sample'; style-src 'self'; worker-src 'none'; upgrade-insecure-requests; report-uri https://q.stripe.com/csp-violation?q=tX2guqYncfomEWe-Mk2AXqXsVToGidy2-03lWTRLHKQk8LH5Df1u7KLOHTP3E079LfXHt4sYD--fS1tg, content-type=application/json, cross-origin-opener-policy-report-only=same-origin; report-to="coop", date=Sat, 22 Mar 2025 08:15:10 GMT, idempotency-key=174263130967976df4f57-1f7c-4a8a-9652-d21acbda77efqCEc25Do, original-request=req_meAsYPd1zisb63, report-to={"group":"coop","max_age":8640,"endpoints":[{"url":"https://q.stripe.com/coop-report"}],"include_subdomains":true}, reporting-endpoints=coop="https://q.stripe.com/coop-report", request-id=req_meAsYPd1zisb63, server=nginx, strict-transport-security=max-age=63072000; includeSubDomains; preload, stripe-should-retry=false, stripe-version=2019-02-19, vary=Origin, x-stripe-priority-routing-enabled=true, x-stripe-routing-context-priority-tier=api-testmode, x-wc=AB} response={"accountId":"acct_1QY7dxQdYzmDIyF0","accountRef":{"storeId":{"address":{"city":"Marktoberdorf","country":"DE","line1":"Schwabenstr. 58","line2":"8","postalCode":"87616","state":"BY"},"displayName":"Office 3c5789da-7307-45d6-a084-aaa28209dd5f","id":"tml_F6ZhQALwDHqrfm","livemode":false,"metadata":{"officeId":"3c5789da-7307-45d6-a084-aaa28209dd5f"}}},"connectionContextId":"tcc_1R5ND0QdYzmDIyF0VaVQGMqN","livemode":false,"readerId":"tmr_F9pwVQjleEa7QU","__redacted_fields":["readerRpcSessionToken","sdkRpcSessionToken","stripeSessionToken"]}"
2025-03-22 09:15:10.384  8303-8516  StripeTerminal          mek.stripe_terminal_example          D  class=AidlRpcClient message=makeRequest service=COTS_SERVICE method=ACTIVATE requestId=1
2025-03-22 09:15:10.439  8520-8520  binder:8520_3           mek.stripe_terminal_example          W  type=1400 audit(0.0:890): avc: denied { getattr } for path="/sys/kernel/tracing/trace_marker" dev="tracefs" ino=8855 scontext=u:r:untrusted_app:s0:c200,c256,c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0 app=mek.stripe_terminal_example
2025-03-22 09:15:10.616  8520-8541  SensorManager           mek.stripe_terminal_example          E  sensor or listener is null
```

</details>

And from the UI:

https://github.com/user-attachments/assets/0eb1e075-c22e-476a-b76c-54a35ad27904

The connection status never changes from `connecting` to either a success or a failure.

**Comment by zontaluca** [comment]
I confirm that I can connect with 4.1.0. Is it planned to fix this problem in the next release (4.4.0)?

**Comment by chr-stripe** [comment]
Thanks for this issue report. I can confirm that we did introduce some logic in the Terminal SDK in version 4.2.0 (and still present in 4.3.0) that would begin to read data from the [`TYPE_ACCELEROMETER`](https://developer.android.com/reference/android/hardware/Sensor#TYPE_ACCELEROMETER) sensor. I'm guessing that the cause of the issue here is that the device you're running on is lacking this particular sensor, which is a bit surprising since accelerometers seem pretty ubiquitous nowadays...

Would you be able to double check for me which sensors are available on the device you're running into this issue on? Looping through all the sensors on the device should be fairly straightforward:

```kotlin
// kotlin
val sensorManager = context.getSystemService(Context.SENSOR_SERVICE) as SensorManager
sensorManager.getSensorList(Sensor.TYPE_ALL).forEach { println(it) }

// java
SensorManager sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
for (Sensor sensor : sensorManager.getSensorList(Sensor.TYPE_ALL)) {
    System.out.println(sensor.getName());
}
```

The list of sensors printed to logcat upon running this code should appear something like:

```
{Sensor name="Dynamic Sensor Manager", vendor="Google", version=1, type=32, maxRange=1.0, resolution=1.0, power=0.001, minDelay=1000}
{Sensor name="LSM6DSV Accelerometer", vendor="STMicro", version=1, type=1, maxRange=156.9064, resolution=0.0047856453, power=0.001, minDelay=5000}
{Sensor name="MMC56X3X Magnetometer", vendor="MEMSIC", version=1, type=2, maxRange=3198.1567, resolution=0.0976, power=0.001, minDelay=10000}
...etc
```

If you can share the list of sensors on the device you're running into this issue on, that would be very helpful!

**Comment by chr-stripe** [comment]
Thank you all for the requested info! We've staged a fix for this issue internally and it will be available in our next release. I'll update this thread once it's published and available for use.

**Comment by chr-stripe** [comment]
This is fixed in the `4.3.1` release which is now available.

**Comment by paolo96** [comment]
Just tried 4.3.1 with Sunmi V3Mix and still experiencing error "sensor or listener is null"

**Comment by chr-stripe** [comment]
The message may still be printed to logcat but the reader connection should still succeed. Are you experiencing the connection still getting stuck?

**Comment by hrueger** [comment]
Hi, I just wanted to test this, however, with the `4.3.1` sdk I get a new error (should I create a separate issue for this?):
```
I/flutter (13054): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
I/flutter (13054): Stripe Secret Key: true
I/flutter (13054): Permission.locationWhenInUse: PermissionStatus.granted
I/flutter (13054): Permission.bluetooth: PermissionStatus.granted
I/flutter (13054): Permission.bluetoothScan: PermissionStatus.granted
I/flutter (13054): Permission.bluetoothConnect: PermissionStatus.granted
I/flutter (13054): Permission.locationWhenInUse: ServiceStatus.enabled
I/flutter (13054): Permission.bluetooth: ServiceStatus.enabled
I/flutter (13054): Connection Status Changed: discovering
I/flutter (13054): Connection Status Changed: notConnected
I/flutter (13054): Connection Status Changed: connecting
I/flutter (13054): Connection Status Changed: notConnected
E/flutter (13054): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: TerminalException: unexpectedSdkError
E/flutter (13054): 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
E/flutter (13054): Otherwise, a callback/listener may leak in case of external cancellation.
E/flutter (13054): See callbackFlow API documentation for the details.
E/flutter (13054): com.stripe.stripeterminal.external.models.TerminalException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
E/flutter (13054): Otherwise, a callback/listener may leak in case of external cancellation.
E/flutter (13054): See callbackFlow API documentation for the details.
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(Unknown Source:89)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(Unknown Source:87)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(Unknown Source:16)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.terminalsession.activate.DefaultTerminalSessionReaderActivator.activateReader(Unknown Source:89)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.terminalsession.connect.ConnectReaderOperation.execute(Unknown Source:105)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.terminalsession.ExternalOperation.run(Unknown Source:16)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(Unknown Source:113)
E/flutter (13054):      at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.a(Unknown Source:0)
E/flutter (13054):      at B.p.run(Unknown Source:244)
E/flutter (13054):      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
E/flutter (13054):      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/flutter (13054):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/flutter (13054):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/flutter (13054):      at java.lang.Thread.run(Thread.java:1012)
E/flutter (13054): 
E/flutter (13054): #0      TerminalPlatform._throwIfIsHostException (package:mek_stripe_terminal/src/platform/terminal_platform.dart:181)
E/flutter (13054): #1      _$TerminalPlatform.connectReader (package:mek_stripe_terminal/src/platform/terminal_platform.api.dart:83)
E/flutter (13054): <asynchronous suspension>
E/flutter (13054): #2      Terminal.connectReader.<anonymous closure> (package:mek_stripe_terminal/src/terminal.dart:164)
E/flutter (13054): <asynchronous suspension>
E/flutter (13054): #3      TerminalHandlers.handleReaderConnection (package:mek_stripe_terminal/src/platform/terminal_handlers.dart:27)
E/flutter (13054): <asynchronous suspension>
E/flutter (13054): #4      _ReadersScreenState._connectReader (package:example/screens/readers_screen.dart:128)
E/flutter (13054): <asynchronous suspension>
E/flutter (13054): #5      StateTools.mutate (package:example/utils/state_tools.dart:71)
E/flutter (13054): <asynchronous suspension>
E/flutter (13054): 
```

**Comment by paolo96** [comment]
> The message may still be printed to logcat but the reader connection should still succeed. Are you experiencing the connection still getting stuck?

yes, still stuck, seeing same error reported by @hrueger and I also see "sensor or listener is null" before that

**Comment by chr-stripe** [comment]
Thank you for the update, we'll look into this some more.

**Comment by chr-stripe** [comment]
This will be addressed in the upcoming `4.4.0` SDK release.

**Comment by sonnguyenhitpay** [comment]
Hi Stripe team 

We're encountering a runtime crash only on release builds of our Android app using Stripe Terminal SDK v4.3.1, when connecting to Tap to Pay readers on a Sunmi V3 Mix device.

Steps to Reproduce:

Start Tap to Pay discovery via Terminal.getInstance().discoverReaders(...)

After receiving discovered readers list, select one and call Terminal.getInstance().connectReader(...)

On debug build → connection is successful 

On release build → throws runtime exception 

Observed Error (Release only):
`
com.stripe.stripeterminal.external.models.TerminalException: 'awaitClose { yourCallbackOrListener.cancel() }' should be used in the end of callbackFlow block.
Otherwise, a callback/listener may leak in case of external cancellation.
`



Device Info:

Device: Sunmi V3 Mix

Sensor present: 
`
{Sensor name="semtech_sx937x_0 SAR Sensor Non-wakeup", vendor="Semtech", version=4112, type=33171005, maxRange=1.0, resolution=0.01, power=0.022, minDelay=0}
Sensor:{Sensor name="semtech_sx937x_0 SAR Sensor Wakeup", vendor="Semtech", version=4112, type=33171005, maxRange=1.0, resolution=0.01, power=0.022, minDelay=0}
`

SDK version: Stripe Terminal Android v4.3.1

Android Target SDK: 34

<img width="1824" alt="Image" src="https://github.com/user-attachments/assets/b58085b0-79a9-40c1-ba76-4e11680c98c2" />
